### ISSUE TITLE
Attempt to call a nil value (global 'NativeUI')

### ISSUE THREAD

**Issue by reesque** [FrazzIe/NativeUILua#20]
I followed the instruction and add client_script '@NativeUI/NativeUI.lua' to __resource.lua. However, whenever I add ```MenuPool = NativeUI.CreatePool()```, it returns this error ```Attempt to call a nil value (global 'NativeUI')```. Any idea why? Thank you.

**Comment by ImBaphomettt** [comment]
Hello, With you tried to start the [MenuExemple ](https://github.com/FrazzIe/NativeUILua/tree/master/MenuExample) provided with NativeUI?

NativeUI resource Is called NativeUI?

**Comment by reesque** [comment]
I actually solved the problem by adding ```client_script 'NativeUI/NativeUI.lua'``` instead of ```client_script '@NativeUI/NativeUI.lua'``` in front of every other client script

**Comment by ImBaphomettt** [comment]
if you issue is solved, you can close this. 👍
