### ISSUE TITLE
failed to load scripts

### ISSUE THREAD

**Issue by Azareeltv** [FrazzIe/NativeUILua#21]
keep getting these errors 

Failed to load script @NativeUI/NativeUI.lua.
Failed to load script  NativeUI.lua.
Failed to load script @NativeUI/NativeUI.lua. 

thats whats comes up in F8

**Comment by ImBaphomettt** [comment]
Hello, Have you properly started the resource ?

Your NativeUI folder should look like this
https://gyazo.com/bbdb2c9fd4467c8137df40f607c0722d

(Without the initialization folder && README.md && NativeUI.json)

**Comment by Azareeltv** [comment]
yeah i can send a screenshot of how thr folder looks but it loads in game and its right in the resource.lua aswell

**Comment by ImBaphomettt** [comment]
Have you touched the NativeUI.lua source code?

What is the server artifacts version? (Https://runtime.fivem.net/artifacts/fivem/)

**Comment by Azareeltv** [comment]
no i havent touched it i have the one from 13th but i can download the latest and try

**Comment by ImBaphomettt** [comment]
Hmm, what is your discord, I think it would be simpler to communique ?

**Comment by Azareeltv** [comment]
here ApexRP#0871 but i found another one and tried that to see if that one gives me errors and it dosent and i can open the menu now

**Comment by ImBaphomettt** [comment]
if you issue is solved, you can close this. 👍
