### ISSUE TITLE
Visual Bug on 10 items

### ISSUE THREAD

**Issue by manups4e** [FrazzIe/NativeUILua#22]
When only 10 items are in the menu the 10th element goes onto the description and you cant see it anymore...
![screenshot 184](https://user-images.githubusercontent.com/4005518/50397684-7a3d1380-0772-11e9-92b7-50cfe71e607d.png)
![screenshot 185](https://user-images.githubusercontent.com/4005518/50397685-7a3d1380-0772-11e9-95e4-155fc36b81ec.png)

**Comment by ImBaphomettt** [comment]
Hello, for my part no problem. 

http://prntscr.com/lzjmow
http://prntscr.com/lzjmr7

* have you updated your NativeUI ?

Can you share the code to you use.

**Comment by manups4e** [comment]
I'll update it again.. let's see :)
I'm using for cycles to create every submenu items

**Comment by ImBaphomettt** [comment]
Can you try this, is telling me if it works perfectly  
```lua
local submenu = _menuPool:AddSubMenu(menu, "Another Menu")
    for i = 1, 69, 1 do
        submenu:AddItem(NativeUI.CreateItem("PageFiller", "Sample description that takes more than one line. Moreso, it takes way more than two lines since it's so long. Wow, check out this length!"))
end
```

it should work perfectly.

**Comment by manups4e** [comment]
I will :)

Il giorno Mer 26 Dic 2018, 13:24 Dylan Malandain <notifications@github.com>
ha scritto:

**Comment by ImBaphomettt** [comment]
if you issue is solved, you can close this. 👍

**Comment by manups4e** [comment]
I'll try it this evening and in case I'll close the issue

Il giorno Mer 26 Dic 2018, 13:39 Dylan Malandain <notifications@github.com>
ha scritto:

**Comment by ImBaphomettt** [comment]
solved ?

**Comment by manups4e** [comment]
yeah sorry 👍 i forgot to close the issue.. doing it now
