### ISSUE TITLE
[FEATURE REQUEST] add a new grid panel (screenshot)

### ISSUE THREAD

**Issue by manups4e** [FrazzIe/NativeUILua#25]
I wanted to ask if it's possible to add this kind of panel like in GTA online 
![screenshot 258](https://user-images.githubusercontent.com/4005518/51793137-09977580-21bc-11e9-8d89-cd836a96dd86.png)

**Comment by ImBaphomettt** [comment]
Hello, this feature is available in my NativeUILua FORK.

https://github.com/iTexZoz/NativeUILua-Reloaded/wiki/Grid-Panel

Have a good day.

**Comment by manups4e** [comment]
> Hello, this feature is available in my NativeUILua FORK.
> 
> https://github.com/iTexZoz/NativeUILua-Reloaded/wiki/Grid-Panel
> 
> Have a good day.

if i use your version.. do i have to change all the menus code format?

**Comment by ImBaphomettt** [comment]
A change will only be necessary for your submenu

Before
```lua
local submenu = _menuPool:AddSubMenu(menu, "Another Menu")
for i = 1, 20, 1 do
  submenu:AddItem(NativeUI.CreateItem("PageFiller", ""))
end
```

After
```lua
local submenu = _menuPool:AddSubMenu(menu, "Another Menu")
for i = 1, 20, 1 do
  submenu.SubMenu:AddItem(NativeUI.CreateItem("PageFiller", ""))
end
```

I invite you to read the FAQ for more information.

https://github.com/iTexZoz/NativeUILua-Reloaded/issues/9

**Comment by manups4e** [comment]
thx :D
