### ISSUE TITLE
Any other item not responding in a submenu

### ISSUE THREAD

**Issue by ThatZiv** [FrazzIe/NativeUILua#26]
I have an issue regarding the usage of `OnSliderChange` in a sub menu. 
Issue: No response when the slider is changed in the submenu.
When I use the code in the main menu, it works fine.
```lua
function SecondMenu(menu)
local submenu = _menuPool:AddSubMenu(menu, "Vehicle Menu")
            local seats = {-1,0,1,2}
            local seat = NativeUI.CreateSliderItem("Seat Index", seats, 1)
         
            seat.OnSliderChange = function(sender, item, index)
                    vehSeat = item:IndexToItem(index)
                    notify(vehSeat)
                    SetPedIntoVehicle(GetPlayerPed(-1), GetVehiclePedIsIn(GetPlayerPed(-1),false), vehSeat)
               
            end
            submenu:AddItem(seat)
        end
```
[Preview](https://gyazo.com/f63a32e0be25d6493e277c8465549a38)
^ Here is what it looks like, not working in a sub menu, but working in as its own in the main menu (normal). Please let me know if this is a bug/issue, or if this is a limitation on sub menus, thanks.

**Comment by ImBaphomettt** [comment]
Hello, to begin, thank you for the attention you have given to NativeUILua,

Unfortunately I don't think I would receive an answer from the original creator of NativeUILua. 

If you need help, if you have found a bug, or if you have a question about NativeUILua, I invite you to check out my NativeUILua fork. I will answer you as soon as possible.

**Comment by ImBaphomettt** [comment]
To answer your question, this is not a problem related to NativeUILua, but to your source code.

```lua
function SecondMenu(menu)
    local submenu = _menuPool:AddSubMenu(menu, "Vehicle Menu")
    local amount = {}
    for i = -1, 2 do amount[i] = i end
    local seat = NativeUI.CreateSliderItem("Seat Index", amount, 1)
    submenu:AddItem(seat)
    submenu.OnSliderChange = function(sender, item, index)
          if item == seat then
            quantity = item:IndexToItem(index)
           print(quantity)
        end
    end
end
```

[Preview](https://gyazo.com/f2cb18406a87de9d6f3d3843752acc0d)

If your problem is solved I invite you to close your issue

Best regarde. Dylan M

**Comment by ThatZiv** [comment]
Thank you Dylan, I appreciate it.
