### ISSUE TITLE
GridPanel is not able to use the complete native

### ISSUE THREAD

**Issue by DevMinkh** [FrazzIe/NativeUILua#8]
Natives
Sets the various freemode face features, e.g. nose length, chin shape. Scale ranges from -1.0 to 1.0.

can u please add negative values aswell? or a way to setup a range for the grid.

LG Minkh

**Comment by FrazzIe** [comment]
the face features go from -1.0 to 1.0?
Edit: `Sets the various freemode face features, e.g. nose length, chin shape. Scale ranges from -1.0 to 1.0`

Yeah i'll fix this, god dammit..
